# Generated by Django 6.0.1 on 2026-01-07 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HipHopSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('pseudonimo', models.CharField(blank=True, max_length=200, verbose_name='Pseudônimo/Nome Artístico')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('cor', models.CharField(choices=[('PRETA', 'Preta'), ('PARDA', 'Parda'), ('BRANCA', 'Branca'), ('INDIGENA', 'Indígena'), ('AMARELA', 'Amarela')], max_length=20, verbose_name='Cor/Raça')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não-binário'), ('O', 'Outro')], max_length=2, verbose_name='Gênero')),
                ('tempo_hiphop', models.CharField(help_text='Ex: 5 anos, 10 anos, desde 2010', max_length=100, verbose_name='Quanto tempo na cultura Hip-Hop')),
                ('atuacao', models.CharField(choices=[('MC', 'MC/Rapper/Cantor'), ('DJ', 'DJ'), ('GRAFITE', 'Grafite'), ('BREAKING', 'Breaking'), ('GRUPO', 'Grupo'), ('CONHECIMENTO', 'Conhecimento'), ('FAS', 'Fãs'), ('CONSUMIDOR', 'Consumidores de produtos do Hip-Hop')], max_length=20, verbose_name='Atuação na Cultura Hip-Hop')),
                ('nome_grupo', models.CharField(blank=True, help_text='Se faz parte de um grupo', max_length=200, verbose_name='Nome do Grupo')),
                ('membros_masculinos', models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de membros masculinos')),
                ('membros_femininos', models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de membros femininos')),
                ('formado', models.BooleanField(default=False, verbose_name='É formado?')),
                ('qual_formacao', models.CharField(blank=True, help_text='Se sim, qual curso/área', max_length=200, verbose_name='Qual formação?')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações adicionais')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pesquisa Hip-Hop',
                'verbose_name_plural': 'Pesquisas Hip-Hop',
                'ordering': ['-criado_em'],
            },
        ),
    ]
